#!/usr/bin/env zsh

[[ "$(uname)" == "Darwin" ]] || { exit 20; } # make sure this is macOS

# Prep
installTo="$(defaults read /opt/script/config.plist installTo)"
source "$installTo/etc/colors.sh"

# Make sure scriptlet is specificed
[[ -z "$1" ]] && { log "${BRED}Error${NC}: ${RED}No target specified${NC}"; exit -100; }

# Parse args
CMD="$1"; shift
ARGS="$*"
#log "C:<$CMD>\t A:<$ARGS>"; echo;  # DEBUG

# Check for 'special' verbs        ✅       ✅       ✅
if [[ "$CMD" == "install" ]]; then     # SPECIAL: `install`
  installScript="$installTo/script/sh/install"
  log "${BMAGENTA}Special: ${CYAN}install:  <${BCYAN}$ARGS${NC}>"
  log "Install script root:  @<$installScript>"


  [[ "$ARGS" == "common" ]] && { { bash "$installScript/brew-list.sh" && log "${BMAGENTA}Special Install: Reports ${GREEN}Complete${NC}"; } \
    || { log "${BMAGENTA}Special Install: Reports ${YELLOW}Finished${NC} **does not indicate success or failure!**"; } }
  [[ "$ARGS" == "kleopatra" ]] && { bash "$installScript/kleopatra.sh"; log "${BMAGENTA}Special Install: ${BGREEN}Caveats pre-satisfied${NC}"; }
  exit 0
elif [[ "$CMD" == "help" ]]; then
  echo "dcd"
  :
fi

# Run the scriptlet
(exec eval '/opt/script/bin/"$CMD" "$ARGS"')
