#!/usr/bin/env zsh

readonly MYNAME="$(basename $0)"
[[ "$(uname)" == "Darwin" ]] || { exit 20; } # make sure this is macOS

# Prep
export installTo="$(defaults read /opt/script/config.plist installTo)"
source "$installTo/etc/colors.sh"

# HELP
help(){
  log "$MYNAME \t(HELP):";
    echo -e "  ⇝ ${BMAGENTA}${MYNAME}${NC} is a CLI utility designed to facilitate common tasks on macOS; it is not designed for use on
    other POSIX systems."
    echo;
    echo -e  "${CYAN}--------${NC}";
    echo -e "${BCYAN}COMMANDS${NC}:"
    echo -e  "${CYAN}--------${NC}";
    echo -e "$(ls $installTo/bin/)"
    [[ "$1" == 'NOEXIT' ]] || exit 0;
}

# Make sure scriptlet is specificed
# shellcheck disable=SC2242
[[ -z "$1" ]] && { (log "${BRED}Error${NC}: ${RED}Missing, unknown, or ambiguous target${NC}" && help "NOEXIT" && echo -e "\n${RED} code${NC}: 101";); exit 101; };

# Parse args

export CMD="$1"; shift
export ARGS="$*";
#export ARGS64="$(echo $* | base64)"
#echo "$(base64 -d "$ARGS64")"; exit 0;
#log "C:<$CMD>\t A:<$ARGS>"; echo;  # DEBUG

# Check for 'special' verbs        ✅       ✅       ✅
[[ "$CMD" == "install" ]]&&{                                                              # SPECIAL: `install`
  installScript="$installTo/script/sh/install";
  log "${BMAGENTA}Special: ${CYAN}install:  <${BCYAN}$ARGS${NC}>";
  log "Install script root:  @<$installScript>";

  [[ "$ARGS" == "update" ||  "$ARGS" == 'update' || "$ARGS" == 'u' ]]&&{
    log "[ $date ] >>> ${CYAN}Manual update of ${BGREEN}homebrew${CYAN} and its components ..."
    log "${BMAGENTA} >> Updating ${GREEN}brew${NC} ..."
    log "$(brew update >/dev/tty)"
    log "${BMAGENTA} >> Updating ${GREEN}components${NC} ..."
    brew outdated | xargs -I{} zsh -c "echo -n {} | awk '{print $NF}'" | xargs -I{} brew upgrade --greedy {};
    log "The command completed with exit code < $? >; n.b.: Please see any above messages for details or "\
        "${BYELLOW}important${NC} messages"
    exit 0;
  };

  [[ "$ARGS" == "common" ]] && { { bash "$installScript/brew-list.sh" && log "${BMAGENTA}Special Install: Reports ${GREEN}Complete${NC}"; }\
    || { log "${BMAGENTA}Special Install: Reports ${YELLOW}finished${NC} **${RED}does not indicate success or failure!**${NC}"; exit 0; }; };

  [[ "$ARGS" == "kleopatra" ]]&&{
    bash "$installScript/kleopatra.sh";
    log "${BMAGENTA}Special Install${NC} --> ${MAGENTA}note${NC}: ${BGREEN}Caveats pre-satisfied${NC}";
  };

   [[ "$ARGS" == "fix" ]]&&{
      log "Executing ${BRED}repair${NC} tasks ...";
      bash "$installScript/fix.sh";
      exec zsh;
    };
};

[[ "$CMD" == "help" ]]&&{                                                                            # SPECIAL: `help`
  help
};

#if [[ -d "$installTo/script/sh/$CMD" ]];then                                    # SPECIAL: searching for alternate commands
#  shift; F="$1";
#  [[ -f "$installTo/script/sh/$F/$CMD" ]]&&{
#    cmdStr="$installTo/script/sh/$F/$CMD $ARGS";
#    log "${BMAGENTA}Special: ${CYAN}exec:  < ${BCYAN}$cmdStr${NC} > $((eval $cmdStr); echo -n $?)";
#    exit $?;
#    };
#fi

  # otherwise... invalid SPECIAL specified
  #log "${BRED}Error${NC}: ${RED}Unable to parse the ${BYELLOW}SPECIAL${NC} provided";
#  exit 1;




# Run the scriptlet
(eval eval "$installTo/bin/$CMD" "$ARGS") || exit $?
exit "$?"  #b Script completed --> exit gracefully with natural return value
