#!/usr/bin/env zsh

# Prep
installTo="$(defaults read /opt/script/config.plist installTo)"
source "$installTo/etc/colors.sh"

# Make sure scriptlet is specificed
[[ -z "$1" ]] && { log "${BRED}Error${NC}: ${RED}No scriptlet specified${NC}"; exit -100; }

# Parse args
CMD="$1"; shift
ARGS="$*"
#log "C:<$CMD>\t A:<$ARGS>"; echo;  # DEBUG

# Check for 'special' commands
if [[ "$CMD" == "install" ]]; then
  log "${BMAGENTA}Special: ${CYAN}install: ${BCYAN}$2${NC}"
  installScript="$installTo/script/sh/install"

  [[ "$ARGS" == "common" ]] && { bash "$installScript/brew-list.sh"; log "${BMAGENTA}Special Install: ${BGREEN}Complete${NC}"; }
  [[ "$ARGS" == "kleopatra" ]] && { bash "$installScript/kleopatra.sh"; log "${BMAGENTA}Special Install: ${BGREEN}Caveats pre-satisfied${NC}"; }
  exit 0

fi

# Run the scriptlet
(exec eval '/opt/script/bin/"$CMD" "$ARGS"')
